name: Build docker image and push it to Docker Hub
run-name: Creating updated Docker image from latest commit ${{ github.sha }}
on:
  push:
    branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update environment values
        run: |
          cat <<EOL >.Rprofile
          source("renv/activate.R")

          Sys.setenv(
            CLIENT_ID = "${{ secrets.SPOTIFY_CLIENT_ID }}",
            CLIENT_SECRET = "${{ secrets.SPOTIFY_CLIENT_SECRET }}",
            REDIRECT_URI = "${{ secrets.REDIRECT_URI }}"
          )
          EOL

      - name: Get Short Hash
        run: |
          short_sha=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$short_sha" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spotify-dashboard:latest,${{ secrets.DOCKER_HUB_USERNAME }}/spotify-dashboard:${{ env.SHORT_SHA }}
